pipeline {
    agent {
        label 'agent-ec2'
    }
    
    tools {
        maven 'maven-tool'
        'dependency-check' 'DC'
        jdk 'jdk-25-tool'
    }
    
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '2')
    }
    
    environment {
        SONAR_SCANNER = tool 'sonarqube-scanner-tool'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building Cart Service...'
                slackSend channel: 'retail-store-sample-aws', message: 'Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}', teamDomain: 'DevOps Workspace', tokenCredentialId: 'slack-token-Jenkins'
                sh """
                    mvn -f src/cart/pom.xml clean package -DskipTests
                """
            }
        }
        
        stage('Unit Tests') {
            steps {
                echo 'Running unit tests...'
                sh """
                    # Skip integration tests because it requires DynamoDB container
                    mvn -f src/cart/pom.xml test -DexcludedGroups=integration
                """
            }
            post {
                always {
                    // Publish test results
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Security & Quality Analysis') {
            parallel {
                stage('OWASP Dependency Check') {
                    steps {
                        echo 'Running OWASP Dependency Check...'
                        dependencyCheck additionalArguments: '''
                            --scan src/cart
                            --format HTML
                            --format JSON
                            --format XML
                            --failOnCVSS 7
                        ''', odcInstallation: 'DC', nvdCredentialsId: 'nvdApiKey-of-Owasp-Dependency-Check'
                    }
                    post {
                        always {
                            dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                        }
                    }
                }
                
                stage('Code Quality') {
                    stages {
                        stage('SonarQube Analysis') {
                            steps {
                                echo 'Running SonarQube analysis...'
                                withSonarQubeEnv('sonarqube-server') {
                                    sh """
                                        ${SONAR_SCANNER}/bin/sonar-scanner \
                                            -Dsonar.projectKey=Retail-Store-Cart-Service \
                                            -Dsonar.sources=src/cart/src/main/java \
                                            -Dsonar.java.binaries=src/cart/target/classes \
                                            -Dsonar.sourceEncoding=UTF-8
                                    """
                                }
                            }
                        }
                        
                        stage('Quality Gate') {
                            steps {
                                echo 'Waiting for Quality Gate...'
                                timeout(time: 10, unit: 'MINUTES') {
                                    waitForQualityGate abortPipeline: true
                                }
                            }
                        }
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh """
                    docker build -f src/cart/Dockerfile -t zohaibwarraich/retail-store-cart-service:${BUILD_NUMBER} .
                """
            }
        }
        
        stage('Trivy Image Scan') {
            steps {
                echo 'Scanning Docker image with Trivy...'
                sh """
                    trivy image \
                        --severity HIGH,CRITICAL \
                        --exit-code 0 \
                        --no-progress \
                        --format template \
                        --template '@/usr/local/share/trivy/templates/html.tpl' \
                        --output trivy-report.html \
                        zohaibwarraich/retail-store-cart-service:${BUILD_NUMBER}
                """
            }
            post {
                always {
                    publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: '.',
                        reportFiles: 'trivy-report.html',
                        reportName: 'Trivy Security Scan Report',
                        reportTitles: 'Trivy Vulnerability Report'
                    ])
                }
            }
        }
        
        stage('Push to DockerHub') {
            steps {
                echo 'Pushing image to DockerHub...'
                withCredentials([usernamePassword(credentialsId: 'docker-token', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                        // echo $PASSWORD | docker login -u $USERNAME --password-stdin
                        docker push zohaibwarraich/retail-store-cart-service:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
    
    post {
        always {
            echo 'Cleaning up...'
            sh """
                docker rmi zohaibwarraich/retail-store-cart-service:${BUILD_NUMBER} || true
            """
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
            slackSend channel: 'retail-store-sample-aws', message: 'Build Success: ${env.JOB_NAME} ${env.BUILD_NUMBER}. \nYou can find the Code quality report, Dependency Check report, Trivy report here: ${env.BUILD_URL}', teamDomain: 'DevOps Workspace', tokenCredentialId: 'slack-token-Jenkins'
        }
        failure {
            echo 'Pipeline failed!'
            slackSend channel: 'retail-store-sample-aws', message: 'Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}. \nYou can find the Code quality report, Dependency Check report, Trivy report here: ${env.BUILD_URL}', teamDomain: 'DevOps Workspace', tokenCredentialId: 'slack-token-Jenkins'
        }
    }
}

