apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: retail-store-services
  namespace: argocd
spec:
  goTemplate: true
  
  # Generators find lists of things (folders, clusters, etc.) and generate Apps for them.
  generators:
  # Looks for any directory inside 'k8s/*' and creates an App for it. This makes adding new services automatic just create a folder in Git.
  - git:
      repoURL: 'https://github.com/zohaibwarraich1/retail-store-sample-app-by-AWS.git'

      revision: HEAD
      directories:
      - path: k8s/*
      - path: k8s/infra
        exclude: true # Exclude the 'infra' folder (managed by the separate App above)
  
  # If you prefer manual control, you can list services explicitly. This is merged with the Git generator.
  - list:
      elements:
      - service: ui
        path: k8s/ui
      - service: catalog
        path: k8s/catalog
      - service: cart
        path: k8s/cart
      - service: checkout
        path: k8s/checkout
      - service: orders
        path: k8s/orders

  # This template is instantiated for every item found by the generators.
  template:
    metadata:
      name: 'retail-store-{{.service}}'
    spec:
      project: retail-store
      source:
        repoURL: 'https://github.com/zohaibwarraich1/retail-store-sample-app-by-AWS.git'
        targetRevision: HEAD
        # Path will be injected from Generator
        path: '{{.path}}'  
        # Recursively apply manifests in subdirectories
        directory:
          recurse: true 
      destination:
        server: https://kubernetes.default.svc
        namespace: retail-store-ns
      syncPolicy:
        automated:
         # Delete K8s resources if file deleted in Git
          prune: true       
          # Revert manual kubectl edits
          selfHeal: true    
        syncOptions:
        - CreateNamespace=true
        - Validate=true  
        # If network issueks or K8s API is busy, retry the sync automatically
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m